### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by RyannDaGreat** [stapuft/anime-couch-mode-activator#1]
What does this do lol, does it modify kissanime.com somehow?

**Comment by stapuft** [comment]
it makes it so when you go onto a page that has a video, said video plays automatically, and goes into fullscreen automatically. 
its a userscript. they inject javascript, html, and css code into websites as they load/shortly after loading. they are usually simple bits of code and can usually be examined by a layman to determine their trustworthiness/edit to the end users liking.
all of this is stated in the readme...

> this is a userscript that allows you to just sit back, and enjoy, it will automatically go fullscreen, and give focus to the video in order to allow keyboard shortcuts to work.
> 
> on top of that, it also adds 2 new FF buttons and 2 new RW buttons one each for 30 seconds, and for 90 seconds, in order to skip the intro songs you dont like or repeat the ones you do, and enable a more..."netflix like" experience, for the "Pirate conissour"

**Comment by stapuft** [comment]
any other questions?
